---
 - hosts: arch
   remote_user: franta
   tasks:
   - name: Update Arch-based instances
     kewlfft.aur.aur:
       upgrade: yes
       use: paru
       update_cache: yes
 - hosts: rocky
   remote_user: franta
   become: yes
   tasks:
   - name: Update RHEL-based instances
     dnf:
       name: "*"
       state: latest
